var canvasEvents = {
	'07-01-2016' : '<a href="http://bmg-club.com/opp-lop-buri.php" target=_blank style="color:#00FFFF;" style="color:#00FFFF;"><img src="http://bmg-club.com/images/logo-calendar.png"> ลพบุรี </a>',
	'07-02-2016' : '<a href="http://bmg-club.com/opp-bangkok-sat.php" target=_blank style="color:#DA70D6;"><img src="http://bmg-club.com/images/logo-calendar.png"> สำนักงานใหญ่<br> </a>',
	'07-03-2016' : '<a href="http://bmg-club.com/opp-3-place.php" target=_blank ><img src="http://bmg-club.com/images/logo-calendar.png"> สระบุรี ลพบุรี <br>ปทุมธานี </a>',
	'07-05-2016' : '<a href="http://bmg-club.com/opp-saraburi.php" target=_blank style="color:#98FB98;" ><img src="http://bmg-club.com/images/logo-calendar.png">  สระบุรี</a>',
	'07-06-2016' : '<a href="http://bmg-club.com/opp-bangkok.php" target=_blank style="color:#DA70D6;" style="color:#DA70D6;"><img src="http://bmg-club.com/images/logo-calendar.png"> สำนักงานใหญ่<br> </a>',
	'07-07-2016' : '<a href="http://bmg-club.com/opp-chanthaburi.php" target=_blank style="color:#FFDEAD;" ><img src="http://bmg-club.com/images/logo-calendar.png"> จันทบุรี </a>',
	'07-08-2016' : '<a href="http://bmg-club.com/opp-lop-buri.php" target=_blank style="color:#00FFFF;" ><img src="http://bmg-club.com/images/logo-calendar.png"> ลพบุรี</a>',
	'07-09-2016' : '<a href="http://bmg-club.com/opp-bangkok-sat.php" target=_blank style="color:#DA70D6;" ><img src="http://bmg-club.com/images/logo-calendar.png"> สำนักงานใหญ่.<br> </a>',
	'07-10-2016' : '<a href="http://bmg-club.com/opp-3-place.php" target=_blank ><img src="http://bmg-club.com/images/logo-calendar.png"> สระบุรี ลพบุรี <br>ปทุมธานี </a>',
	'07-12-2016' : '<a href="http://bmg-club.com/opp-saraburi.php" target=_blank style="color:#98FB98;" ><img src="http://bmg-club.com/images/logo-calendar.png">  สระบุรี </a>',
	'07-13-2016' : '<a href="http://bmg-club.com/opp-bangkok.php" target=_blank style="color:#DA70D6;" ><img src="http://bmg-club.com/images/logo-calendar.png"> สำนักงานใหญ่<br> </a>',
	'07-14-2016' : '<a href="http://bmg-club.com/opp-chanthaburi.php" target=_blank style="color:#FFDEAD;" style="color:#FFDEAD;"><img src="http://bmg-club.com/images/logo-calendar.png"> จันทบุรี </a>',
	'07-15-2016' : '<a href="http://bmg-club.com/opp-lop-buri.php" target=_blank style="color:#00FFFF;" ><img src="http://bmg-club.com/images/logo-calendar.png"> ลพบุรี </a>',
	'07-16-2016' : '<a href="http://bmg-club.com/opp-bangkok-sat.php" target=_blank style="color:#DA70D6;" ><img src="http://bmg-club.com/images/logo-calendar.png"> สำนักงานใหญ่<br> </a>',
	'07-17-2016' : '<a href="http://bmg-club.com/opp-3-place.php" target=_blank ><img src="http://bmg-club.com/images/logo-calendar.png"> สระบุรี ลพบุรี <br>ปทุมธานี </a>',
	'07-19-2016' : '<a href="http://bmg-club.com/opp-saraburi.php" target=_blank style="color:#98FB98;" ><img src="http://bmg-club.com/images/logo-calendar.png">  สระบุรี </a>',
	'07-20-2016' : '<a href="http://bmg-club.com/opp-bangkok.php" target=_blank style="color:#DA70D6;" ><img src="http://bmg-club.com/images/logo-calendar.png"> สำนักงานใหญ่<br> </a>',
	'07-21-2016' : '<a href="http://bmg-club.com/opp-chanthaburi.php" target=_blank style="color:#FFDEAD;" ><img src="http://bmg-club.com/images/logo-calendar.png"> จันทบุรี</a>',
	'07-22-2016' : '<a href="http://bmg-club.com/opp-lop-buri.php" target=_blank style="color:#00FFFF;" ><img src="http://bmg-club.com/images/logo-calendar.png"> ลพบุรี </a>',
	'07-23-2016' : '<a href="http://bmg-club.com/opp-bangkok-sat.php" target=_blank style="color:#DA70D6;" ><img src="http://bmg-club.com/images/logo-calendar.png"> สำนักงานใหญ่<br> </a>',
	'07-24-2016' : '<a href="http://bmg-club.com/opp-3-place.php" target=_blank ><img src="http://bmg-club.com/images/logo-calendar.png"> สระบุรี ลพบุรี <br>ปทุมธานี</a>',
	'07-26-2016' : '<a href="http://bmg-club.com/opp-saraburi.php" target=_blank style="color:#98FB98;"><img src="http://bmg-club.com/images/logo-calendar.png"> สระบุรี </a>',
	'07-27-2016' : '<a href="http://bmg-club.com/opp-bangkok.php" target=_blank style="color:#DA70D6;" ><img src="http://bmg-club.com/images/logo-calendar.png"> สำนักงานใหญ่<br> </a>',
	'07-28-2016' : '<a href="http://bmg-club.com/opp-chanthaburi.php" target=_blank style="color:#FFDEAD;" ><img src="http://bmg-club.com/images/logo-calendar.png"> จันทบุรี </a>',
	'07-29-2016' : '<a href="http://bmg-club.com/vietnam.php" target=_blank ><img src="http://bmg-club.com/images/logo-calendar.png"> ท่องเที่ยว เวียดนาม </a>',
	'07-30-2016' : '<a href="http://bmg-club.com/vietnam.php" target=_blank ><img src="http://bmg-club.com/images/logo-calendar.png"> ท่องเที่ยว เวียดนาม<br> </a>',
	'07-31-2016' : '<a href="http://bmg-club.com/vietnam.php" target=_blank ><img src="http://bmg-club.com/images/logo-calendar.png"> ท่องเที่ยว เวียดนาม</a>',


	'08-02-2016' : '<a href="http://bmg-club.com/opp-saraburi.php" target=_blank style="color:#98FB98;" ><img src="http://bmg-club.com/images/logo-calendar.png">  สระบุรี </a>',
	'08-03-2016' : '<a href="http://bmg-club.com/opp-bangkok.php" target=_blank style="color:#DA70D6;" ><img src="http://bmg-club.com/images/logo-calendar.png"> สำนักงานใหญ่<br> </a>',
	'08-04-2016' : '<a href="http://bmg-club.com/opp-chanthaburi.php" target=_blank style="color:#FFDEAD;" style="color:#FFDEAD;"><img src="http://bmg-club.com/images/logo-calendar.png"> จันทบุรี </a>',
	'08-05-2016' : '<a href="http://bmg-club.com/opp-lop-buri.php" target=_blank style="color:#00FFFF;" ><img src="http://bmg-club.com/images/logo-calendar.png"> ลพบุรี </a>',
	'08-06-2016' : '<a href="http://bmg-club.com/opp-bangkok-sat.php" target=_blank style="color:#DA70D6;" ><img src="http://bmg-club.com/images/logo-calendar.png"> สำนักงานใหญ่<br> </a>',
	'08-07-2016' : '<a href="http://bmg-club.com/opp-3-place.php" target=_blank ><img src="http://bmg-club.com/images/logo-calendar.png"> สระบุรี ลพบุรี <br>ปทุมธานี </a>',

	'08-09-2016' : '<a href="http://bmg-club.com/opp-saraburi.php" target=_blank style="color:#98FB98;" ><img src="http://bmg-club.com/images/logo-calendar.png">  สระบุรี </a>',
	'08-10-2016' : '<a href="http://bmg-club.com/opp-bangkok.php" target=_blank style="color:#DA70D6;" ><img src="http://bmg-club.com/images/logo-calendar.png"> สำนักงานใหญ่<br> </a>',
	'08-11-2016' : '<a href="http://bmg-club.com/opp-chanthaburi.php" target=_blank style="color:#FFDEAD;" style="color:#FFDEAD;"><img src="http://bmg-club.com/images/logo-calendar.png"> จันทบุรี </a>',
	'08-12-2016' : '<a href="http://bmg-club.com/opp-lop-buri.php" target=_blank style="color:#00FFFF;" ><img src="http://bmg-club.com/images/logo-calendar.png"> ลพบุรี </a>',
	'08-13-2016' : '<a href="http://bmg-club.com/opp-bangkok-sat.php" target=_blank style="color:#DA70D6;" ><img src="http://bmg-club.com/images/logo-calendar.png"> สำนักงานใหญ่<br> </a>',
	'08-14-2016' : '<a href="http://bmg-club.com/opp-3-place.php" target=_blank ><img src="http://bmg-club.com/images/logo-calendar.png"> สระบุรี ลพบุรี <br>ปทุมธานี </a>',

	'08-16-2016' : '<a href="http://bmg-club.com/opp-saraburi.php" target=_blank style="color:#98FB98;" ><img src="http://bmg-club.com/images/logo-calendar.png">  สระบุรี </a>',
	'08-17-2016' : '<a href="http://bmg-club.com/opp-bangkok.php" target=_blank style="color:#DA70D6;" ><img src="http://bmg-club.com/images/logo-calendar.png"> สำนักงานใหญ่<br> </a>',
	'08-18-2016' : '<a href="http://bmg-club.com/opp-chanthaburi.php" target=_blank style="color:#FFDEAD;" style="color:#FFDEAD;"><img src="http://bmg-club.com/images/logo-calendar.png"> จันทบุรี </a>',
	'08-19-2016' : '<a href="http://bmg-club.com/opp-lop-buri.php" target=_blank style="color:#00FFFF;" ><img src="http://bmg-club.com/images/logo-calendar.png"> ลพบุรี </a>',
	'08-20-2016' : '<a href="http://bmg-club.com/opp-bangkok-sat.php" target=_blank style="color:#DA70D6;" ><img src="http://bmg-club.com/images/logo-calendar.png"> สำนักงานใหญ่<br> </a>',
	'08-21-2016' : '<a href="http://bmg-club.com/opp-3-place.php" target=_blank ><img src="http://bmg-club.com/images/logo-calendar.png"> สระบุรี ลพบุรี <br>ปทุมธานี </a>',

	'08-23-2016' : '<a href="http://bmg-club.com/opp-saraburi.php" target=_blank style="color:#98FB98;" ><img src="http://bmg-club.com/images/logo-calendar.png">  สระบุรี </a>',
	'08-24-2016' : '<a href="http://bmg-club.com/opp-bangkok.php" target=_blank style="color:#DA70D6;" ><img src="http://bmg-club.com/images/logo-calendar.png"> สำนักงานใหญ่<br> </a>',
	'08-25-2016' : '<a href="http://bmg-club.com/opp-chanthaburi.php" target=_blank style="color:#FFDEAD;" style="color:#FFDEAD;"><img src="http://bmg-club.com/images/logo-calendar.png"> จันทบุรี </a>',
	'08-26-2016' : '<a href="http://bmg-club.com/opp-lop-buri.php" target=_blank style="color:#00FFFF;" ><img src="http://bmg-club.com/images/logo-calendar.png"> ลพบุรี </a>',
	'08-27-2016' : '<a href="http://bmg-club.com/opp-bangkok-sat.php" target=_blank style="color:#DA70D6;" ><img src="http://bmg-club.com/images/logo-calendar.png"> สำนักงานใหญ่<br> </a>',
	'08-28-2016' : '<a href="http://bmg-club.com/opp-3-place.php" target=_blank ><img src="http://bmg-club.com/images/logo-calendar.png"> สระบุรี ลพบุรี <br>ปทุมธานี </a>',

	'08-30-2016' : '<a href="http://bmg-club.com/opp-saraburi.php" target=_blank style="color:#98FB98;" ><img src="http://bmg-club.com/images/logo-calendar.png">  สระบุรี </a>',
	'08-31-2016' : '<a href="http://bmg-club.com/opp-bangkok.php" target=_blank style="color:#DA70D6;" ><img src="http://bmg-club.com/images/logo-calendar.png"> สำนักงานใหญ่<br> </a>',

	};
